var global=window;window.debug=!0;var MicroformatError=global.MicroformatError=function(c){var a=this===global?new MicroformatError.F:this;MicroformatError.superclass.constructor.apply(a,arguments);a.name="MicroformatError";a.message=c||"";return a};inherit(MicroformatError,Error);MicroformatError.F=function(){};
var ui=global.ui=global.ui||{},_isEmptyElement=global.Utils.Dom.isEmptyElement,WAElement=ui.WAElement=function(c,a){global.DEBUG&&(typeof c==undefType?console.error("[ui.WAElement] new:: \u042d\u043b\u0435\u043c\u0435\u043d\u0442 \u0434\u043e\u043b\u0436\u0435\u043d \u0431\u044b\u0442\u044c \u0437\u0430\u0434\u0430\u043d"):"object"!=typeof c&&console.error("[ui.WAElement] new:: \u042d\u043b\u0435\u043c\u0435\u043d\u0442 \u0434\u043e\u043b\u0436\u0435\u043d \u0442\u0438\u043f\u0430 Object"));WAElement.formatTest(c);
var b=this,d=++WAElement._nextUid;b.options={};b.DOMElement=c;b.owner=a;b.isInit=!1;b.uid=function(){return d};b.init=function(){if(b.isInit)return!1;var a=b.DOMElement,e=a.getAttribute("itemid");if(e&&"urn:onlife:apps"===e.substr(0,15)&&!b.templateLoaded)return ResourceManager.loadResource(e,function(d){function c(a){"object"==typeof d&&(new d.constructor(a)).init()}function g(a,b){var d=document.createDocumentFragment(),c=d.appendChild(document.createElement("div"));c.innerHTML=a;c=c.firstChild;
$A(c.attributes).forEach(function(a){"class"==a.name&&$A(c.classList).forEach(function(a){b.classList.add(a)});b.setAttribute(a.name,a.value)});$A(c.childNodes).forEach(function(a){b.appendChild(a)});c.innerHTML="";d=c=null}_isEmptyElement(a)?"object"==typeof d?ResourceManager.loadTextResource(e+"/"+d.html,function(d){""==d?console.error("Empty answer for '"+e+"' request"):(g(d,a),c(a),b.init())},function(){console.error("Some error fired while sending '"+e+"' request")}):(g(d,a),c(a),b.init()):(c(a),
b.init())}),b.templateLoaded=!0,!1;b.id=a.id||(a.id=randomString(9)+"_");b.properties=a.properties;b.\u0441omponents=b.properties.component;$A(b.\u0441omponents).forEach(function(a){var c=a.getAttribute("itemtype");if(null===c)throw new MicroformatError("itemscope attribute need");c.split(" ").forEach(function(c){var d=MicroformatConstructors[c];d?(new d(a,b)).init():console.error("unkonown component type : "+c)})});a.addEventListener("show",function(){var b=a.getAttribute("style");b&&(b=b.replace(": ",
":").replace(" :",":").replace("display:none",""),a.setAttribute("style",b));this.classList.add("select")});a.addEventListener("hide",function(){this.classList.remove("select")});return b.isInit=!0}};
WAElement.formatTest=function(c){if(null===c.getAttribute("itemscope"))throw MicroformatError("itemscope attribute need");var a=c.getAttribute("itemtype");if(null===a)throw MicroformatError("itemscope attribute need");if(!c.microdataType&&~a.indexOf(c.microdataType))throw MicroformatError("element must implement '"+c.microdataType+"' microdata type except of '"+a+"'");};WAElement._nextUid=0;WAElement.prototype.microdataType="onlifeschema.org/WAElement";
WAElement.prototype.show=function(){this.DOMElement.dispatchEvent(new CustomEvent("show",{bubbles:!1}))};WAElement.prototype.hide=function(){this.DOMElement.dispatchEvent(new CustomEvent("hide",{bubbles:!1}))};
var WAForm=ui.WAForm=function(c){function a(a){var b=a.target,c=b.action,d=c.split("?"),d=d.replace(/\{\[(.*?)\]\}/gi,function(a,c){if(b[c])return b[c].value});global.DEBUG&&console.log(c+"?"+d);a.stopPropagation();a.preventDefault();return!1}var b=this;WAForm.superclass.constructor.apply(b,arguments);b.forms=null;var d=b.init;b.init=function(){if(!d.apply(b,arguments))return!1;b.forms=$A(b.properties.form);b.forms.forEach(function(b){b.onsubmit=a});b.DOMElement.addEventListener("submit",a)}};
inherit(WAForm,ui.WAElement);WAForm.prototype.microdataType="onlifeschema.org/WAForm";
var WAMenu=ui.WAMenu=function(c){var a=this;WAMenu.superclass.constructor.apply(a,arguments);var b=a.DOMElement.getAttribute(WAMenu.menuEventAttribute);!b&&global.DEBUG&&console.error("WAMenu element must have value in '"+WAMenu.menuEventAttribute+"' attribute");var d=bubbleEventListener(WAMenu.menuEventDetailAttribute,function(c,d,f){c=new CustomEvent(b,{bubbles:!0,cancelable:!0,detail:f});a.DOMElement.dispatchEvent(c)}),f=a.init;a.init=function(){if(!1===f.apply(a,arguments))return!1;if(b)(a.menuItems=
$A(a.properties.menuItem)).forEach(function(a){a.addEventListener("click",d,!1);a.addEventListener("touchstart",d,!1);a.addEventListener("touchend",d,!1)})}};inherit(WAMenu,ui.WAElement);WAMenu.menuEventAttribute="data-menu-event";WAMenu.menuEventDetailAttribute="data-menu-detail";WAMenu.prototype.microdataType="onlifeschema.org/WAMenu";
var WATabs=ui.WATabs=function(c){var a=this;WATabs.superclass.constructor.apply(a,arguments);a.subTabs=null;a.tabsCount=0;a.currentTab=-1;var b=a.init;a.init=function(){if(!1===b.apply(a,arguments))return!1;a.initTabsSpetialProperties(a.DOMElement);a.subTabs=$A(a.properties.tab);a.tabsCount=a.subTabs.length;a.subTabs.forEach(function(b,c){if(b.classList.contains("select"))a.currentTab=c;b.addEventListener("show",function(){if(a.currentTab!=c)a.DOMElement.currentTab=c;this.classList.add("select")});
b.addEventListener("hide",function(){this.classList.remove("select")})});a.DOMElement.addEventListener("tabchange",function(b){var c=a.subTabs[b.prevTab],e=a.subTabs[b.currentTab];c&&c.dispatchEvent(new CustomEvent("hide",{bubbles:!1,cancelable:!0}));e&&e.dispatchEvent(new CustomEvent("show",{bubbles:!1,cancelable:!0}));b.stopPropagation()});a.DOMElement.addEventListener("menuopentab",function(b){var c=parseInt(b.detail);if(!isNaN(c)&&a.DOMElement.currentTab!=c)a.DOMElement.currentTab=c;b.stopPropagation()});
a.DOMElement.currentTab=a.currentTab}};inherit(WATabs,ui.WAElement);WATabs.prototype.microdataType="onlifeschema.org/WATabs";WATabs.prototype.showTab=function(c){var a=this.currentTab,b=new CustomEvent("tabchange",{bubbles:!0,cancelable:!0});c>=this.subTabs.length&&(c=this.subTabs.length-1);this.currentTab=b.currentTab=c;b.prevTab=a;this.DOMElement.dispatchEvent(b)};
WATabs.prototype.initTabsSpetialProperties=function(c){var a=this;Object.defineProperties(c,{currentTab:{get:function(){return a.currentTab},set:function(b){isNaN(b=parseInt(b))||a.showTab(b);return a.currentTab},ielt8:!0},tabCount:{get:function(){return a.tabsCount},ielt8:!0}});c.getcurrentTab&&c.addBehavior&&c.addBehavior("class.ui.WATabs.htc")};
var WebApplication=ui.WebApplication=function(c){var a=this;WebApplication.superclass.constructor.apply(a,arguments);a.authForm=null;a.account={status:{login:!1}};var b=a.init;a.init=function(){if(!1===b.apply(a,arguments))return!1}};inherit(WebApplication,ui.WAElement);WebApplication.prototype.microdataType="onlifeschema.org/WebApplication";WebApplication.prototype.showAuthForm=function(){this.authForm&&this.authForm.dispatchEvent(new CustomEvent("show",{bubbles:!0,cancelable:!0}))};
var ImageGallery=ui.ImageGallery=function(c){var a=this;ImageGallery.superclass.constructor.apply(a,arguments);a.imageCount=0;a.currentImage=-1;var b=a.init;a.init=function(){if(!1===b.apply(a,arguments))return!1;a.openImage=a.properties.primaryImageOfPage[0];a.images=a.properties.associatedMedia;a.imageCount=a.images.length;a.DOMElement.addEventListener("showimage",function(b){var c=$A(a.images)[a.currentImage],e=b.detail;c&&c.classList.remove("select");if(e)e.classList.add("select"),a.currentImage=
$A(a.images).indexOf(e);if(0>a.currentImage||!e)a.currentImage=0,e=$A(a.images)[0];else if(a.currentImage>=a.imageCount)a.currentImage=a.imageCount-1,e=$A(a.images)[a.currentImage];a.openImage.properties.contentURL[0].itemValue=e.properties.contentURL[0].itemValue;a.openImage.properties.caption[0].itemValue=e.properties.caption[0].itemValue;a.openImage.properties.description[0].itemValue=e.properties.description[0].itemValue;b.stopPropagation()});$A(a.images).forEach(function(b){b.addEventListener("click",
a.previewOnClick,!1);b.addEventListener("touchstart",a.previewOnClick,!1);b.addEventListener("touchend",a.previewOnClick,!1);b.classList.contains("select")&&b.dispatchEvent(new Event("click"))})}};inherit(ImageGallery,ui.WAElement);ImageGallery.prototype.microdataType="schema.org/ImageGallery";ImageGallery.prototype.previewOnClick=function(){this.dispatchEvent(new CustomEvent("showimage",{bubbles:!0,cancelable:!0,detail:this}))};
global.MicroformatConstructors={"onlifeschema.org/WebApplication":ui.WebApplication,"onlifeschema.org/WAElement":ui.WAElement,"onlifeschema.org/WATabs":ui.WATabs,"onlifeschema.org/WAMenu":ui.WAMenu,"onlifeschema.org/WAForm":ui.WAForm,"schema.org/ImageGallery":ui.ImageGallery};